{% import "template_utils.f90" as template_utils with context %}
! -----------------
! Loader generated by glad {{ gen_info.version }} on {{ gen_info.when }}
!
! SPDX-License-Identifier: (WTFPL OR CC0-1.0) AND Apache-2.0
!
! Generator: {{ gen_info.generator_name }}
! Specification: {{ gen_info.specification }}
! Extensions: {{ gen_info.extensions|length }}
!
! APIs:
{% for info in gen_info.info %}
!  - {{ info }}
{% endfor %}
!
! Options:
{% for name, value in gen_info.options.items() %}
!  - {{ name }} = {{ value }}
{% endfor %}
!
! Commandline:
!    {{ gen_info.commandline }}
!
! Online:
!    {{ gen_info.online }}
!
! -----------------

module gl
    use, intrinsic :: iso_c_binding

    implicit none
    public
    save

    ! -------------
    ! Kinds
    ! -------------

    integer, parameter :: GLbyte = c_signed_char
    integer, parameter :: GLubyte = c_signed_char
    integer, parameter :: GLchar = c_char
    integer, parameter :: GLcharARB = c_char
    integer, parameter :: GLboolean = c_signed_char

    integer, parameter :: GLshort = c_short
    integer, parameter :: GLushort = c_short

    integer, parameter :: GLint = c_int
    integer, parameter :: GLuint = c_int
    integer, parameter :: GLint64 = c_int64_t
    integer, parameter :: GLuint64 = c_int64_t
    integer, parameter :: GLint64EXT = c_int64_t
    integer, parameter :: GLuint64EXT = c_int64_t

    integer, parameter :: GLintptr = c_intptr_t
    integer, parameter :: GLsizeiptr = c_size_t
    integer, parameter :: GLintptrARB = c_intptr_t
    integer, parameter :: GLsizeiptrARB = c_size_t

    integer, parameter :: GLsizei = GLint
    integer, parameter :: GLclampx = c_int
    integer, parameter :: GLfixed = GLint
    integer, parameter :: GLhalf = c_short
    integer, parameter :: GLhalfNV = c_short
    integer, parameter :: GLhalfARB = c_short

    integer, parameter :: GLenum = c_int
    integer, parameter :: GLbitfield = c_int

    integer, parameter :: GLfloat = c_float
    integer, parameter :: GLdouble = c_double
    integer, parameter :: GLclampf = c_float
    integer, parameter :: GLclampd = c_double

    integer, parameter :: GLvdpauSurfaceNV = GLintptr

    abstract interface
        subroutine GLDEBUGPROC(source, type, id, severity, length, message, userParam) bind(C)
            import
            implicit none
            integer(kind=GLenum), value :: source
            integer(kind=GLenum), value :: type
            integer(kind=GLuint), value :: id
            integer(kind=GLenum), value :: severity
            integer(kind=GLsizei), value :: length
            character(len=1,kind=GLchar), dimension(*) :: message
            type(c_ptr), value :: userParam
        end subroutine GLDEBUGPROC

        subroutine GLDEBUGPROCARB(source, type, id, severity, length, message, userParam) bind(C)
            import
            implicit none
            integer(kind=GLenum), value :: source
            integer(kind=GLenum), value :: type
            integer(kind=GLuint), value :: id
            integer(kind=GLenum), value :: severity
            integer(kind=GLsizei), value :: length
            character(len=1,kind=GLchar), dimension(*) :: message
            type(c_ptr), value :: userParam
        end subroutine GLDEBUGPROCARB

        subroutine GLDEBUGPROCKHR(source, type, id, severity, length, message, userParam) bind(C)
            import
            implicit none
            integer(kind=GLenum), value :: source
            integer(kind=GLenum), value :: type
            integer(kind=GLuint), value :: id
            integer(kind=GLenum), value :: severity
            integer(kind=GLsizei), value :: length
            character(len=1,kind=GLchar), dimension(*) :: message
            type(c_ptr), value :: userParam
        end subroutine GLDEBUGPROCKHR

        subroutine GLDEBUGPROCAMD(source, type, id, severity, length, message, userParam) bind(C)
            import
            implicit none
            integer(kind=GLenum), value :: source
            integer(kind=GLenum), value :: type
            integer(kind=GLuint), value :: id
            integer(kind=GLenum), value :: severity
            integer(kind=GLsizei), value :: length
            character(len=1,kind=GLchar), dimension(*) :: message
            type(c_ptr), value :: userParam
        end subroutine GLDEBUGPROCAMD

        subroutine GLVULKANPROCNV() bind(C)
        end subroutine GLVULKANPROCNV
    end interface

    abstract interface
        function GLADloadfunc(name) result(procaddr)
            use, intrinsic :: iso_c_binding
            implicit none
            character(len=*, kind=c_char), intent(in) :: name
            type(c_funptr) :: procaddr
        end function GLADloadfunc
    end interface

    ! -------------
    ! Enumerations
    ! -------------

    {% for enum in feature_set.enums %}
    {{ enum|enum_type }}, parameter :: {{ enum.name }} &
        = {{ enum|enum_value }}
    {% endfor %}

    ! -------------
    ! Functions
    ! -------------

    {% for command in feature_set.commands %}
    procedure({{ command.name|proc_interface }}), pointer, private :: &
        {{ command.name|proc_pointer }}
    {% endfor %}

    ! -------------
    ! Function interfaces
    ! -------------

    abstract interface
        {% for command in feature_set.commands %}
        {{ command|proc_type }} {{ command.name|proc_interface }}({{ command|params }}) bind(C)
            import
            implicit none
            {% for param in command.params %}
            {{ param.type|type_interface }} :: {{ param.name|identifier }}
            {% endfor %}
            {% if command is returning %}

            {{ command|return_type_interface }} :: {{ command.name|proc_interface }}
            {% endif %}
        end {{ command|proc_type }} {{ command.name|proc_interface }}
        {% endfor %}
    end interface

    private :: c_strlen, c_f_string, f_c_string, c_f_strpointer

    interface c_strlen
        pure function c_ptr_strlen(cstr) result(length) bind(C, name="strlen")
            import
            implicit none
            type(c_ptr), value, intent(in) :: cstr
            integer(kind=c_size_t) :: length
        end function c_ptr_strlen
        pure function c_char_strlen(cstr) result(length) bind(C, name="strlen")
            import
            implicit none
            character(len=1,kind=c_char), dimension(*), intent(in) :: cstr
            integer(kind=c_size_t) :: length
        end function c_char_strlen
    end interface c_strlen

    interface c_f_string
        module procedure c_str_f_string, c_ptr_f_string
    end interface c_f_string

    contains

        {% for command in feature_set.commands %}
        {{ command|proc_type }} {{ command.name|proc_impl }}({{ command|params }}) {{ 'result(res)' if command is returning }}
            implicit none
            {% for param in command.params %}
            {{ param.type|type_impl }} :: {{ param.name|identifier }}
            {% endfor %}
            {% if command is returning %}

            {{ command|return_type_impl }} :: res
            {% if command is requiring_int_res %}
            {{ command|return_type_interface }} :: int_res
            {% endif %}
            {% endif %}

            {% if command is returning %}
            {% if command is requiring_int_res %}
            int_res = {{ command.name|proc_pointer }}({{ command|params }})
            {{ command|intermediate_result }}
            {% else %}
            res = {{ command.name|proc_pointer }}({{ command|params }})
            {% endif %}
            {% else %}
            call {{ command.name|proc_pointer }}({{ command|params }})
            {% endif %}
        end {{ command|proc_type }} {{ command.name|proc_impl }}
        {% endfor %}

        {% for api in feature_set.info.apis %}
        function gladLoad{{ api|api }}(loadfn) result(version)
            implicit none
            procedure(GLADloadfunc) :: loadfn
            integer :: version
            
            version = 0

            {% for command in feature_set.commands %}
            call c_f_procpointer(loadfn("{{ command.name }}"),&
                                 {{ command.name|proc_pointer }})
            {% endfor %}
        end function gladLoad{{ api|api }}
        {% endfor %}

        subroutine c_f_strpointer(cptr, fptr)
            implicit none
            type(c_ptr), intent(in) :: cptr
            character(len=:,kind=c_char), pointer, intent(out) :: fptr

            character(len=c_strlen(cptr),kind=c_char), pointer :: temp
            call c_f_pointer(cptr, temp)
            fptr => temp
        end subroutine c_f_strpointer

        pure function f_c_string(fstr) result(cstr)
            implicit none
            character(len=*,kind=c_char), intent(in) :: fstr
            character(len=1,kind=c_char), dimension(:), allocatable :: cstr

            integer :: c_length
            integer :: i


        end function f_c_string

        pure function c_str_f_string(cstr) result(fstr)
            implicit none
            character(len=1,kind=c_char), dimension(*), intent(in) :: cstr
            character(len=c_strlen(cstr),kind=c_char) :: fstr

            integer :: i

            do i = 1,len(fstr)
                fstr(i:i) = cstr(i)
            end do
        end function c_str_f_string

        function c_ptr_f_string(cptr) result(fstr)
            implicit none
            type(c_ptr), intent(in) :: cptr
            character(len=:,kind=c_char), allocatable :: fstr

            character(len=1,kind=c_char), dimension(:), pointer :: cstr
            integer :: i

            call c_f_pointer(cptr, cstr, [c_strlen(cptr)])
            allocate(character(len=len(cstr)) :: fstr)
            do i = 1,len(cstr)
                fstr(i:i) = cstr(i)
            end do
        end function c_ptr_f_string
end module gl

