{% import "template_utils.f90" as template_utils with context %}
{% block TODO %}
! -----------------
! Loader generated by glad {{ gen_info.version }} on {{ gen_info.when }}
!
! SPDX-License-Identifier: (WTFPL OR CC0-1.0) AND Apache-2.0
!
! Generator: {{ gen_info.generator_name }}
! Specification: {{ gen_info.specification }}
! Extensions: {{ gen_info.extensions|length }}
!
! APIs:
{% for info in gen_info.info %}
!  - {{ info }}
{% endfor %}
!
! Options:
{% for name, value in gen_info.options.items() %}
!  - {{ name }} = {{ value }}
{% endfor %}
!
! Commandline:
!    {{ gen_info.commandline }}
!
! Online:
!    {{ gen_info.online }}
!
! -----------------
{% endblock %}

module gl
    use, intrinsic :: iso_c_binding

    implicit none
    !private
    save

    ! -------------
    ! Kinds
    ! -------------

    integer, parameter, public :: GLbyte = c_signed_char
    integer, parameter, public :: GLubyte = c_signed_char
    integer, parameter, public :: GLchar = c_char
    integer, parameter, public :: GLcharARB = c_char
    integer, parameter, public :: GLboolean = c_signed_char

    integer, parameter, public :: GLshort = c_short
    integer, parameter, public :: GLushort = c_short

    integer, parameter, public :: GLint = c_int
    integer, parameter, public :: GLuint = c_int
    integer, parameter, public :: GLint64 = c_int64_t
    integer, parameter, public :: GLuint64 = c_int64_t
    integer, parameter, public :: GLint64EXT = c_int64_t
    integer, parameter, public :: GLuint64EXT = c_int64_t

    integer, parameter, public :: GLintptr = c_intptr_t
    integer, parameter, public :: GLsizeiptr = c_size_t
    integer, parameter, public :: GLintptrARB = c_intptr_t
    integer, parameter, public :: GLsizeiptrARB = c_size_t

    integer, parameter, public :: GLsizei = GLint
    integer, parameter, public :: GLclampx = c_int
    integer, parameter, public :: GLfixed = GLint
    integer, parameter, public :: GLhalf = c_short
    integer, parameter, public :: GLhalfNV = c_short
    integer, parameter, public :: GLhalfARB = c_short

    integer, parameter, public :: GLenum = c_int
    integer, parameter, public :: GLbitfield = c_int

    integer, parameter, public :: GLfloat = c_float
    integer, parameter, public :: GLdouble = c_double
    integer, parameter, public :: GLclampf = c_float
    integer, parameter, public :: GLclampd = c_double

    integer, parameter, public :: GLvdpauSurfaceNV = GLintptr

    abstract interface
        subroutine GLDEBUGPROC(source, type, id, severity, length, message, userParam)
            import
            implicit none
            integer(kind=GLenum), value :: source
            integer(kind=GLenum), value :: type
            integer(kind=GLuint), value :: id
            integer(kind=GLenum), value :: severity
            integer(kind=GLsizei), value :: length
            character(len=1,kind=GLchar), dimension(*) :: message
            type(c_ptr), value :: userParam
        end subroutine GLDEBUGPROC
    end interface

    abstract interface
        subroutine GLDEBUGPROCARB(source, type, id, severity, length, message, userParam)
            import
            implicit none
            integer(kind=GLenum), value :: source
            integer(kind=GLenum), value :: type
            integer(kind=GLuint), value :: id
            integer(kind=GLenum), value :: severity
            integer(kind=GLsizei), value :: length
            character(len=1,kind=GLchar), dimension(*) :: message
            type(c_ptr), value :: userParam
        end subroutine GLDEBUGPROCARB
    end interface

    abstract interface
        subroutine GLDEBUGPROCKHR(source, type, id, severity, length, message, userParam)
            import
            implicit none
            integer(kind=GLenum), value :: source
            integer(kind=GLenum), value :: type
            integer(kind=GLuint), value :: id
            integer(kind=GLenum), value :: severity
            integer(kind=GLsizei), value :: length
            character(len=1,kind=GLchar), dimension(*) :: message
            type(c_ptr), value :: userParam
        end subroutine GLDEBUGPROCKHR
    end interface

    abstract interface
        subroutine GLDEBUGPROCAMD(source, type, id, severity, length, message, userParam)
            import
            implicit none
            integer(kind=GLenum), value :: source
            integer(kind=GLenum), value :: type
            integer(kind=GLuint), value :: id
            integer(kind=GLenum), value :: severity
            integer(kind=GLsizei), value :: length
            character(len=1,kind=GLchar), dimension(*) :: message
            type(c_ptr), value :: userParam
        end subroutine GLDEBUGPROCAMD
    end interface

    abstract interface
        subroutine GLVULKANPROCNV()
        end subroutine GLVULKANPROCNV
    end interface

    abstract interface
        function GLADloadfunc(name) result(func)
            use, intrinsic :: iso_c_binding
            implicit none
            character(len=*, kind=c_char), intent(in) :: name
            type(c_funptr)                            :: func
        end function GLADloadfunc
    end interface

    ! -------------
    ! Enumerations
    ! -------------

    {% for enum in feature_set.enums %}
    {{ enum|enum_type }}, parameter, public :: {{ enum.name }} &
                                            = {{ enum|enum_value }}
    {% endfor %}

    ! -------------
    ! Functions
    ! -------------

    {% for command in feature_set.commands %}
    procedure({{ command.name|proc_interface }}), pointer :: &
        {{ command.name|proc_pointer }}
    {% endfor %}

    ! -------------
    ! Function interfaces
    ! -------------

    {% for command in feature_set.commands %}
    abstract interface
        {{ command|proc_type }} {{ command.name|proc_interface }}({{ command|params }}) bind(C)
            import
            implicit none
            {% for param in command.params %}
            {{ param.type|type }} :: {{ param.name|identifier }}
            {% endfor %}
            {% if command is returning %}

            {{ command|func_type }} :: {{ command.name|proc_interface }}
            {% endif %}
        end {{ command|proc_type }} {{ command.name|proc_interface }}
    end interface
    {% endfor %}

    contains

        {% for command in feature_set.commands %}
        {% endfor %}

        {% for api in feature_set.info.apis %}
        function gladLoad{{ api|api }}(loadfn) result(version)
            implicit none
            procedure(GLADloadfunc) :: loadfn
            integer :: version
            
            version = 0

            {% for command in feature_set.commands %}
            call c_f_procpointer(loadfn("{{ command.name }}"),&
                                 {{ command.name|proc_pointer }})
            {% endfor %}
        end function gladLoad{{ api|api }}
        {% endfor %}

end module gl

