on: [push, pull_request]

name: glad2

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      WINEDLLOVERRIDES: mscoree,mshtml=
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install dependencies
        run: |
          # Install wine
          sudo mkdir -pm755 /etc/apt/keyrings
          wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
          sudo dpkg --add-architecture i386
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
          sudo apt-get update
          sudo apt install --install-recommends winehq-stable
          # Install remaining dependencies
          sudo apt-get install gcc g++ gcc-mingw-w64 g++-mingw-w64 rustc libglfw3-dev winetricks xvfb libxxf86vm-dev libxi-dev libxcursor-dev libxinerama-dev
      - name: Setup environment
        run: winetricks nocrashdialog
      - name: Run Tests
        run: PRINT_MESSAGE=1 xvfb-run --auto-servernum ./utility/test.sh
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-report.xml
          comment_mode: off
